<?php

use Illuminate\Database\Seeder;
use App\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $secondaryRegion = [
            array('name'=>'Bermuda','secondary_region_id'=>'1'),
            array('name'=>'Canada','secondary_region_id'=>'1'),
            array('name'=>'Saint Pierre and Miquelon','secondary_region_id'=>'1'),
            array('name'=>'United States','secondary_region_id'=>'1'),
            array('name'=>'Azerbaijan','secondary_region_id'=>'2'),
            array('name'=>'Kazakhstan','secondary_region_id'=>'2'),
            array('name'=>'Kyrgyzstan','secondary_region_id'=>'2'),
            array('name'=>'Mongolia','secondary_region_id'=>'2'),
            array('name'=>'New Caledonia','secondary_region_id'=>'2'),
            array('name'=>'Tajikistan','secondary_region_id'=>'2'),
            array('name'=>'Turkmenistan','secondary_region_id'=>'2'),
            array('name'=>'Uzbekistan','secondary_region_id'=>'2'),
            array('name'=>'China','secondary_region_id'=>'3'),
            array('name'=>'Hong Kong','secondary_region_id'=>'3'),
            array('name'=>'Japan','secondary_region_id'=>'3'),
            array('name'=>"Korea, Democratic People's Republic of",'secondary_region_id'=>'3'),
            array('name'=>'Korea, Republic of','secondary_region_id'=>'3'),
            array('name'=>'Macau','secondary_region_id'=>'3'),
            array('name'=>'Taiwan','secondary_region_id'=>'3'),
            array('name'=>'American Samoa','secondary_region_id'=>'4'),
            array('name'=>'Antarctica','secondary_region_id'=>'4'),
            array('name'=>'Australia','secondary_region_id'=>'4'),
            array('name'=>'British Indian Ocean Territory','secondary_region_id'=>'4'),
            array('name'=>'Christmas Island','secondary_region_id'=>'4'),
            array('name'=>'Cocos (Keeling) Islands','secondary_region_id'=>'4'),
            array('name'=>'MacCocos (Keeling) Islandsau','secondary_region_id'=>'4'),
            array('name'=>'Fiji','secondary_region_id'=>'4'),
            array('name'=>'French Polynesia','secondary_region_id'=>'4'),
            array('name'=>'French Southern Territories','secondary_region_id'=>'4'),
            array('name'=>'Guam','secondary_region_id'=>'4'),
            array('name'=>'Heard Island and McDonald Islands','secondary_region_id'=>'4'),
            array('name'=>'Kiribati','secondary_region_id'=>'4'),
            array('name'=>'Marshall Islands','secondary_region_id'=>'4'),
            array('name'=>'Micronesia, Federated States of','secondary_region_id'=>'4'),
            array('name'=>'Nauru','secondary_region_id'=>'4'),
            array('name'=>'New Zealand','secondary_region_id'=>'4'),
            array('name'=>'Niue','secondary_region_id'=>'4'),
            array('name'=>'Norfolk Island','secondary_region_id'=>'4'),
            array('name'=>'Northern Mariana Islands','secondary_region_id'=>'4'),
            array('name'=>'Palau','secondary_region_id'=>'4'),
            array('name'=>'Papua New Guinea','secondary_region_id'=>'4'),
            array('name'=>'Pitcairn Islands','secondary_region_id'=>'4'),
            array('name'=>'Reunion','secondary_region_id'=>'4'),
            array('name'=>'Samoa','secondary_region_id'=>'4'),
            array('name'=>'Solomon Islands','secondary_region_id'=>'4'),
            array('name'=>'Timor-Leste','secondary_region_id'=>'4'),
            array('name'=>'Tokelau','secondary_region_id'=>'4'),
            array('name'=>'Tonga','secondary_region_id'=>'4'),
            array('name'=>'Tuvalu','secondary_region_id'=>'4'),
            array('name'=>'United States Minor Outlying Islands','secondary_region_id'=>'4'),
            array('name'=>'Vanuatu','secondary_region_id'=>'4'),
            array('name'=>'Wallis and Futuna','secondary_region_id'=>'4'),
            array('name'=>'Afghanistan','secondary_region_id'=>'5'),
            array('name'=>'Bangladesh','secondary_region_id'=>'5'),
            array('name'=>'Bhutan','secondary_region_id'=>'5'),
            array('name'=>'India','secondary_region_id'=>'5'),
            array('name'=>'Maldives','secondary_region_id'=>'5'),
            array('name'=>'Nepal','secondary_region_id'=>'5'),
            array('name'=>'Pakistan','secondary_region_id'=>'5'),
            array('name'=>'Sri Lanka','secondary_region_id'=>'5'),
            array('name'=>'Brunei Darussalam','secondary_region_id'=>'6'),
            array('name'=>'Cambodia','secondary_region_id'=>'6'),
            array('name'=>'Indonesia','secondary_region_id'=>'6'),
            array('name'=>"Lao People's Democratic Republic",'secondary_region_id'=>'6'),
            array('name'=>'Malaysia','secondary_region_id'=>'6'),
            array('name'=>'Myanmar','secondary_region_id'=>'6'),
            array('name'=>'Philippines','secondary_region_id'=>'6'),
            array('name'=>'Singapore','secondary_region_id'=>'6'),
            array('name'=>'Thailand','secondary_region_id'=>'6'),
            array('name'=>'Vietnam','secondary_region_id'=>'6'),
            array('name'=>'Belarus','secondary_region_id'=>'7'),
            array('name'=>'Bosnia and Herzegovina','secondary_region_id'=>'7'),
            array('name'=>'Bulgaria','secondary_region_id'=>'7'),
            array('name'=>'Croatia','secondary_region_id'=>'7'),
            array('name'=>'Estonia','secondary_region_id'=>'7'),
            array('name'=>'Georgia','secondary_region_id'=>'7'),
            array('name'=>'Greece','secondary_region_id'=>'7'),
            array('name'=>'Hungary','secondary_region_id'=>'7'),
            array('name'=>'Macedonia','secondary_region_id'=>'7'),
            array('name'=>'Moldova, Republic of','secondary_region_id'=>'7'),
            array('name'=>'Montenegro','secondary_region_id'=>'7'),
            array('name'=>'Poland','secondary_region_id'=>'7'),
            array('name'=>'Serbia','secondary_region_id'=>'7'),
            array('name'=>'Slovakia','secondary_region_id'=>'7'),
            array('name'=>'Slovenia','secondary_region_id'=>'7'),
            array('name'=>'Svalbard and Jan Mayen','secondary_region_id'=>'7'),
            array('name'=>'Turkey','secondary_region_id'=>'7'),
            array('name'=>'Ukraine','secondary_region_id'=>'7'),
            array('name'=>'Albania','secondary_region_id'=>'8'),
            array('name'=>'Armenia','secondary_region_id'=>'8'),
            array('name'=>'Romania','secondary_region_id'=>'8'),
            array('name'=>'Russian Federation','secondary_region_id'=>'8'),
            array('name'=>'Sweden','secondary_region_id'=>'8'),
            array('name'=>'Aland Islands','secondary_region_id'=>'9'),
            array('name'=>'Andorra','secondary_region_id'=>'9'),
            array('name'=>'Austria','secondary_region_id'=>'9'),
            array('name'=>'Belgium','secondary_region_id'=>'9'),
            array('name'=>'Cyprus','secondary_region_id'=>'9'),
            array('name'=>'Czech Republic','secondary_region_id'=>'9'),
            array('name'=>'Denmark','secondary_region_id'=>'9'),
            array('name'=>'Faroe Islands','secondary_region_id'=>'9'),
            array('name'=>'Finland','secondary_region_id'=>'9'),
            array('name'=>'France','secondary_region_id'=>'9'),
            array('name'=>'Germany','secondary_region_id'=>'9'),
            array('name'=>'Gibraltar','secondary_region_id'=>'9'),
            array('name'=>'Greenland','secondary_region_id'=>'9'),
            array('name'=>'Guernsey','secondary_region_id'=>'9'),
            array('name'=>'Holy See (Vatican City State)','secondary_region_id'=>'9'),
            array('name'=>'Iceland','secondary_region_id'=>'9'),
            array('name'=>'Ireland','secondary_region_id'=>'9'),
            array('name'=>'Isle of Man','secondary_region_id'=>'9'),
            array('name'=>'Israel','secondary_region_id'=>'9'),
            array('name'=>'Italy','secondary_region_id'=>'9'),
            array('name'=>'Jersey','secondary_region_id'=>'9'),
            array('name'=>'Latvia','secondary_region_id'=>'9'),
            array('name'=>'Liechtenstein','secondary_region_id'=>'9'),
            array('name'=>'Lithuania','secondary_region_id'=>'9'),
            array('name'=>'Luxembourg','secondary_region_id'=>'9'),
            array('name'=>'Malta','secondary_region_id'=>'9'),
            array('name'=>'Monaco','secondary_region_id'=>'9'),
            array('name'=>'Netherlands','secondary_region_id'=>'9'),
            array('name'=>'Norway','secondary_region_id'=>'9'),
            array('name'=>'Portugal','secondary_region_id'=>'9'),
            array('name'=>'San Marino','secondary_region_id'=>'9'),
            array('name'=>'Spain','secondary_region_id'=>'9'),
            array('name'=>'Switzerland','secondary_region_id'=>'9'),
            array('name'=>'United Kingdom','secondary_region_id'=>'9'),
            array('name'=>'Angola','secondary_region_id'=>'10'),
            array('name'=>'Benin','secondary_region_id'=>'10'),
            array('name'=>'Botswana','secondary_region_id'=>'10'),
            array('name'=>'Burkina Faso','secondary_region_id'=>'10'),
            array('name'=>'Burundi','secondary_region_id'=>'10'),
            array('name'=>'Cameroon','secondary_region_id'=>'10'),
            array('name'=>'Cape Verde','secondary_region_id'=>'10'),
            array('name'=>'Central African Republic','secondary_region_id'=>'10'),
            array('name'=>'Chad','secondary_region_id'=>'10'),
            array('name'=>'Comoros','secondary_region_id'=>'10'),
            array('name'=>'Congo','secondary_region_id'=>'10'),
            array('name'=>'Congo, The Democratic Republic of the','secondary_region_id'=>'10'),
            array('name'=>"Côte D'Ivoire",'secondary_region_id'=>'10'),
            array('name'=>'Equatorial Guinea','secondary_region_id'=>'10'),
            array('name'=>'Eritrea','secondary_region_id'=>'10'),
            array('name'=>'Ethiopia','secondary_region_id'=>'10'),
            array('name'=>'Gabon','secondary_region_id'=>'10'),
            array('name'=>'Gambia','secondary_region_id'=>'10'),
            array('name'=>'Ghana','secondary_region_id'=>'10'),
            array('name'=>'Guinea','secondary_region_id'=>'10'),
            array('name'=>'Guinea-Bissau','secondary_region_id'=>'10'),
            array('name'=>'Kenya','secondary_region_id'=>'10'),
            array('name'=>'Lesotho','secondary_region_id'=>'10'),
            array('name'=>'Liberia','secondary_region_id'=>'10'),
            array('name'=>'Madagascar','secondary_region_id'=>'10'),
            array('name'=>'Malawi','secondary_region_id'=>'10'),
            array('name'=>'Mali','secondary_region_id'=>'10'),
            array('name'=>'Mauritania','secondary_region_id'=>'10'),
            array('name'=>'Mauritius','secondary_region_id'=>'10'),
            array('name'=>'Mayotte','secondary_region_id'=>'10'),
            array('name'=>'Mozambique','secondary_region_id'=>'10'),
            array('name'=>'Namibia','secondary_region_id'=>'10'),
            array('name'=>'Niger','secondary_region_id'=>'10'),
            array('name'=>'Nigeria','secondary_region_id'=>'10'),
            array('name'=>'Rwanda','secondary_region_id'=>'10'),
            array('name'=>'Saint Helena','secondary_region_id'=>'10'),
            array('name'=>'Sao Tome and Principe','secondary_region_id'=>'10'),
            array('name'=>'Senegal','secondary_region_id'=>'10'),
            array('name'=>'Seychelles','secondary_region_id'=>'10'),
            array('name'=>'Sierra Leone','secondary_region_id'=>'10'),
            array('name'=>'South Africa','secondary_region_id'=>'10'),
            array('name'=>'South Sudan','secondary_region_id'=>'10'),
            array('name'=>'Swaziland','secondary_region_id'=>'10'),
            array('name'=>'Tanzania, United Republic of','secondary_region_id'=>'10'),
            array('name'=>'Togo','secondary_region_id'=>'10'),
            array('name'=>'Uganda','secondary_region_id'=>'10'),
            array('name'=>'Western Sahara','secondary_region_id'=>'10'),
            array('name'=>'Zambia','secondary_region_id'=>'10'),
            array('name'=>'Zimbabwe','secondary_region_id'=>'10'),
            array('name'=>'Bahrain','secondary_region_id'=>'11'),
            array('name'=>'Djibouti','secondary_region_id'=>'11'),
            array('name'=>'Iran, Islamic Republic of','secondary_region_id'=>'11'),
            array('name'=>'Iraq','secondary_region_id'=>'11'),
            array('name'=>'Jordan','secondary_region_id'=>'11'),
            array('name'=>'Kuwait','secondary_region_id'=>'11'),
            array('name'=>'Lebanon','secondary_region_id'=>'11'),
            array('name'=>'Oman','secondary_region_id'=>'11'),
            array('name'=>'Palestinian Territory','secondary_region_id'=>'11'),
            array('name'=>'Qatar','secondary_region_id'=>'11'),
            array('name'=>'Saudi Arabia','secondary_region_id'=>'11'),
            array('name'=>'Somalia','secondary_region_id'=>'11'),
            array('name'=>'Sudan','secondary_region_id'=>'11'),
            array('name'=>'Syrian Arab Republic','secondary_region_id'=>'11'),
            array('name'=>'United Arab Emirates','secondary_region_id'=>'11'),
            array('name'=>'Yemen','secondary_region_id'=>'11'),
            array('name'=>'Algeria','secondary_region_id'=>'12'),
            array('name'=>'Egypt','secondary_region_id'=>'12'),
            array('name'=>'Libya','secondary_region_id'=>'12'),
            array('name'=>'Morocco','secondary_region_id'=>'12'),
            array('name'=>'Tunisia','secondary_region_id'=>'12'),
            array('name'=>'French Guiana','secondary_region_id'=>'13'),
            array('name'=>'Anguilla','secondary_region_id'=>'14'),
            array('name'=>'Antigua and Barbuda','secondary_region_id'=>'14'),
            array('name'=>'Argentina','secondary_region_id'=>'14'),
            array('name'=>'Aruba','secondary_region_id'=>'14'),
            array('name'=>'Bahamas','secondary_region_id'=>'14'),
            array('name'=>'Barbados','secondary_region_id'=>'14'),
            array('name'=>'Belize','secondary_region_id'=>'14'),
            array('name'=>'Bolivia','secondary_region_id'=>'14'),
            array('name'=>'Bouvet Island','secondary_region_id'=>'14'),
            array('name'=>'Brazil','secondary_region_id'=>'14'),
            array('name'=>'Cayman Islands','secondary_region_id'=>'14'),
            array('name'=>'Chile','secondary_region_id'=>'14'),
            array('name'=>'Colombia','secondary_region_id'=>'14'),
            array('name'=>'Costa Rica','secondary_region_id'=>'14'),
            array('name'=>'Cuba','secondary_region_id'=>'14'),
            array('name'=>'Dominica','secondary_region_id'=>'14'),
            array('name'=>'Dominican Republic','secondary_region_id'=>'14'),
            array('name'=>'Ecuador','secondary_region_id'=>'14'),
            array('name'=>'El Salvador','secondary_region_id'=>'14'),
            array('name'=>'Falkland Islands (Malvinas)','secondary_region_id'=>'14'),
            array('name'=>'Grenada','secondary_region_id'=>'14'),
            array('name'=>'Guadeloupe','secondary_region_id'=>'14'),
            array('name'=>'Guatemala','secondary_region_id'=>'14'),
            array('name'=>'Guyana','secondary_region_id'=>'14'),
            array('name'=>'Haiti','secondary_region_id'=>'14'),
            array('name'=>'Honduras','secondary_region_id'=>'14'),
            array('name'=>'Jamaica','secondary_region_id'=>'14'),
            array('name'=>'Martinique','secondary_region_id'=>'14'),
            array('name'=>'Montserrat','secondary_region_id'=>'14'),
            array('name'=>'Netherlands Antilles','secondary_region_id'=>'14'),
            array('name'=>'Nicaragua','secondary_region_id'=>'14'),
            array('name'=>'Panama','secondary_region_id'=>'14'),
            array('name'=>'Paraguay','secondary_region_id'=>'14'),
            array('name'=>'Peru','secondary_region_id'=>'14'),
            array('name'=>'Puerto Rico','secondary_region_id'=>'14'),
            array('name'=>'Saint Barthelemy','secondary_region_id'=>'14'),
            array('name'=>'Saint Kitts and Nevis','secondary_region_id'=>'14'),
            array('name'=>'Saint Lucia','secondary_region_id'=>'14'),
            array('name'=>'Saint Martin','secondary_region_id'=>'14'),
            array('name'=>'Saint Vincent and the Grenadines','secondary_region_id'=>'14'),
            array('name'=>'South Georgia and the South Sandwich Islands','secondary_region_id'=>'14'),
            array('name'=>'Suriname','secondary_region_id'=>'14'),
            array('name'=>'Trinidad and Tobago','secondary_region_id'=>'14'),
            array('name'=>'Turks and Caicos Islands','secondary_region_id'=>'14'),
            array('name'=>'Uruguay','secondary_region_id'=>'14'),
            array('name'=>'Venezuela','secondary_region_id'=>'14'),
            array('name'=>'Virgin Islands, British','secondary_region_id'=>'14'),
            array('name'=>'Virgin Islands, U.S.','secondary_region_id'=>'14'),
        ];
        foreach ($secondaryRegion as $secondayRegionRow) {
            Country::firstOrCreate([
                'name' => $secondayRegionRow['name'],
                'fk_secondary_region_id' => $secondayRegionRow['secondary_region_id'],
            ]);
        }
    }
}
